# Site Information
title               : "White Rose Repointing"
description         : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur non odio ullamcorper, dignissim ante sed, molestie eros. Sed hendrerit molestie ante. Morbi ullamcorper nunc sit amet lacus sodales, et mattis orci ultrices."
url                 : "https://adyanmuhammad.github.io/whiterose-workspace/"
phone               : "07856721738"
mail                : "beaumontdanny@googlemail.com"


# Where things are
source              : .
destination         : ./_site

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false